# Logfile created on 2021-10-25 09:13:50 +0000 by logger.rb/v1.4.2
{"severity":"ERROR","time":"2021-10-25T09:13:50.686Z","correlation_id":"acde22c65773e0a368b4ce59ae987a1c","exception.class":"Sidekiq::Worker::EnqueueFromTransactionError","exception.message":"`AuthorizedProjectUpdate::ProjectCreateWorker.perform_async` cannot be called inside a transaction as this can lead to\nrace conditions when the worker runs before the transaction is committed and\ntries to access a model that has not been saved yet.\n\nUse an `after_commit` hook, or include `AfterCommitQueue` and use a `run_after_commit` block instead.\n","exception.backtrace":["config/initializers/forbid_sidekiq_in_transactions.rb:25:in `block (2 levels) in \u003cmodule:NoEnqueueingFromTransactions\u003e'","app/workers/concerns/application_worker.rb:94:in `perform_async'","app/services/projects/create_service.rb:139:in `setup_authorizations'","app/services/projects/create_service.rb:115:in `after_create_actions'","app/services/projects/create_service.rb:71:in `block in execute'","lib/gitlab/application_context.rb:74:in `block in use'","lib/gitlab/application_context.rb:74:in `use'","lib/gitlab/application_context.rb:27:in `with_context'","app/services/projects/create_service.rb:70:in `execute'","app/services/concerns/measurable.rb:35:in `execute'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:59:in `create_project'","app/models/concerns/stepable.rb:14:in `call'","app/models/concerns/stepable.rb:14:in `block in execute_steps'","app/models/concerns/stepable.rb:13:in `each'","app/models/concerns/stepable.rb:13:in `inject'","app/models/concerns/stepable.rb:13:in `execute_steps'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:27:in `execute'","(eval):3:in `block (2 levels) in run_file'","lib/gitlab/database/load_balancing/connection_proxy.rb:119:in `block in write_using_load_balancer'","lib/gitlab/database/load_balancing/load_balancer.rb:107:in `block in read_write'","lib/gitlab/database/load_balancing/load_balancer.rb:167:in `retry_with_backoff'","lib/gitlab/database/load_balancing/load_balancer.rb:105:in `read_write'","lib/gitlab/database/load_balancing/connection_proxy.rb:118:in `write_using_load_balancer'","lib/gitlab/database/load_balancing/connection_proxy.rb:70:in `transaction'","lib/gitlab/database.rb:271:in `block in transaction'","lib/gitlab/database.rb:270:in `transaction'","lib/tasks/gitlab/db.rake:66:in `block (3 levels) in \u003ctop (required)\u003e'"],"user.username":null,"tags.program":"web","tags.locale":"en","tags.feature_category":null,"tags.correlation_id":"acde22c65773e0a368b4ce59ae987a1c"}
{"severity":"ERROR","time":"2021-10-25T09:13:50.726Z","correlation_id":"acde22c65773e0a368b4ce59ae987a1c","exception.class":"Sidekiq::Worker::EnqueueFromTransactionError","exception.message":"`Projects::PostCreationWorker.perform_async` cannot be called inside a transaction as this can lead to\nrace conditions when the worker runs before the transaction is committed and\ntries to access a model that has not been saved yet.\n\nUse an `after_commit` hook, or include `AfterCommitQueue` and use a `run_after_commit` block instead.\n","exception.backtrace":["config/initializers/forbid_sidekiq_in_transactions.rb:25:in `block (2 levels) in \u003cmodule:NoEnqueueingFromTransactions\u003e'","app/workers/concerns/application_worker.rb:94:in `perform_async'","app/services/projects/create_service.rb:119:in `after_create_actions'","app/services/projects/create_service.rb:71:in `block in execute'","lib/gitlab/application_context.rb:74:in `block in use'","lib/gitlab/application_context.rb:74:in `use'","lib/gitlab/application_context.rb:27:in `with_context'","app/services/projects/create_service.rb:70:in `execute'","app/services/concerns/measurable.rb:35:in `execute'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:59:in `create_project'","app/models/concerns/stepable.rb:14:in `call'","app/models/concerns/stepable.rb:14:in `block in execute_steps'","app/models/concerns/stepable.rb:13:in `each'","app/models/concerns/stepable.rb:13:in `inject'","app/models/concerns/stepable.rb:13:in `execute_steps'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:27:in `execute'","(eval):3:in `block (2 levels) in run_file'","lib/gitlab/database/load_balancing/connection_proxy.rb:119:in `block in write_using_load_balancer'","lib/gitlab/database/load_balancing/load_balancer.rb:107:in `block in read_write'","lib/gitlab/database/load_balancing/load_balancer.rb:167:in `retry_with_backoff'","lib/gitlab/database/load_balancing/load_balancer.rb:105:in `read_write'","lib/gitlab/database/load_balancing/connection_proxy.rb:118:in `write_using_load_balancer'","lib/gitlab/database/load_balancing/connection_proxy.rb:70:in `transaction'","lib/gitlab/database.rb:271:in `block in transaction'","lib/gitlab/database.rb:270:in `transaction'","lib/tasks/gitlab/db.rake:66:in `block (3 levels) in \u003ctop (required)\u003e'"],"user.username":null,"tags.program":"web","tags.locale":"en","tags.feature_category":null,"tags.correlation_id":"acde22c65773e0a368b4ce59ae987a1c"}
{"severity":"ERROR","time":"2021-10-25T09:13:51.347Z","correlation_id":"acde22c65773e0a368b4ce59ae987a1c","exception.class":"Gitlab::Git::PreReceiveError","exception.message":"Internal API unreachable","exception.backtrace":["lib/gitlab/gitaly_client/operation_service.rb:358:in `user_commit_files'","lib/gitlab/git/repository.rb:895:in `block in multi_action'","lib/gitlab/git/wraps_gitaly_errors.rb:7:in `wrapped_gitaly_errors'","lib/gitlab/git/repository.rb:894:in `multi_action'","app/models/repository.rb:827:in `block in multi_action'","app/models/repository.rb:810:in `with_cache_hooks'","app/models/repository.rb:827:in `multi_action'","app/models/repository.rb:791:in `create_file'","app/services/files/create_service.rb:16:in `create_transformed_commit'","app/services/files/create_service.rb:10:in `create_commit!'","app/services/commits/create_service.rb:30:in `execute'","app/services/projects/create_service.rb:162:in `create_readme'","app/services/projects/create_service.rb:121:in `after_create_actions'","app/services/projects/create_service.rb:71:in `block in execute'","lib/gitlab/application_context.rb:74:in `block in use'","lib/gitlab/application_context.rb:74:in `use'","lib/gitlab/application_context.rb:27:in `with_context'","app/services/projects/create_service.rb:70:in `execute'","app/services/concerns/measurable.rb:35:in `execute'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:59:in `create_project'","app/models/concerns/stepable.rb:14:in `call'","app/models/concerns/stepable.rb:14:in `block in execute_steps'","app/models/concerns/stepable.rb:13:in `each'","app/models/concerns/stepable.rb:13:in `inject'","app/models/concerns/stepable.rb:13:in `execute_steps'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:27:in `execute'","(eval):3:in `block (2 levels) in run_file'","lib/gitlab/database/load_balancing/connection_proxy.rb:119:in `block in write_using_load_balancer'","lib/gitlab/database/load_balancing/load_balancer.rb:107:in `block in read_write'","lib/gitlab/database/load_balancing/load_balancer.rb:167:in `retry_with_backoff'","lib/gitlab/database/load_balancing/load_balancer.rb:105:in `read_write'","lib/gitlab/database/load_balancing/connection_proxy.rb:118:in `write_using_load_balancer'","lib/gitlab/database/load_balancing/connection_proxy.rb:70:in `transaction'","lib/gitlab/database.rb:271:in `block in transaction'","lib/gitlab/database.rb:270:in `transaction'","lib/tasks/gitlab/db.rake:66:in `block (3 levels) in \u003ctop (required)\u003e'"],"user.username":null,"tags.program":"web","tags.locale":"en","tags.feature_category":null,"tags.correlation_id":"acde22c65773e0a368b4ce59ae987a1c"}
